name: verticaliser
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.1.2=py38_1
  - pandas=0.25.3
  - pandas-datareader=0.8.1
  - pyfinance=1.2.7
  - requests=2.22.0
  - scikit-learn=0.22
  - scipy=1.3.2
  - seaborn=0.9.0=py_2
  - statsmodels=0.10.2
  - pyodbc=4.0.27
  - python=3.8.0
  - sqlite=3.30.1

